spring:
  profiles:
    active: dev
  application:
    name: obras-publicas-api
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
